### ISSUE TITLE
does not work with 4.2

### ISSUE THREAD

**Issue by lnxbil** [Crivaledaz/Mattermost-LDAP#10]
Hi,

I'm running Mattermost 4.2 and the gitlab url from which I should get redirected is `oauth/gitlab/login` which does not exist in the source. If I manually remap the url in `nginx` to display the `index.php`, i see the login and get `Congratulation you are authenticated !`, net nothing else.

Can you confirm, that Mattermost-LDAP works with 4.2?

Best,
LnxBil

**Comment by Crivaledaz** [comment]
Hi, 

Thanks you for your feedback, I am sorry for the delay, I am a bit overload this time.

I have not yet upgraded Mattermost to 4.2, but I am running Mattermost 4.1 and it works well. I think your problem come from the Nginx configuration. In fact, when you click the Gitlab sign in button on Mattermost, Mattermost is trying to redirect you to : http://OAUTHSERVER/authorize.php?response_type=code&client_id=123456789&state=azertyuiop. However, if you are not already connected on Oauth, autorize.php stores the request and redirect you to index.php where you must sign in with your LDAP login. If your credentials are valid, you come back to the authorize.php page where you are asked to authorize Mattermost to access your data.

When you directly access the index.php page, you can sign in with your LDAP credentials, but index.php cannot redirect you to authorize.php, so you are redirected to a simple and useless text, because Mattermost-LDAP does not know from which client you came. So you need to configure Nginx to keep data in the URL when it redirects user.

If you want to be sure Mattermost-LDAP is working with your Mattermost 4.2, I suggest you to disable your Nginx for test.

If you have another question, feel free to ask, I will try to answer quickly.

Regards,

Crivaledaz

**Comment by lnxbil** [comment]
Thank you for your feedback. I fixed my problem by installing gitlab and doing authentication with it - I needed it for the weekend.
