### ISSUE TITLE
Mishandled redirect to oauth/gitlab/login

### ISSUE THREAD

**Issue by mlazarov** [Crivaledaz/Mattermost-LDAP#17]
Hey!

Thank for the effort to support LDAP for Mattermost!

I'm having issue with the latest Mattemost version (4.3.0)

The Mattermost server is installed on https://chat.mydomain.com/
The LDAP oauth setup is installed on https://chat.mydomain.com/oauth/

The issue I'm having is that the  "Sign in with: Gitlab" link points to: 
https://chat.mydomain.com/oauth/gitlab/login

and there is nothing to handle this url - I'm getting error 404

May be mattermost changed something or I'm missing some part of the configuration?

Martin

**Comment by Crivaledaz** [comment]
Hi,

I never update to Mattermost 4.3.0 (actually, I am no longer on this project in my company). However, your problem seems due to a misconfiguration of the Oauth server in the Mattermost admin panel. 

Can you check the url you have provided in Gitlab section (on Mattermost). According to your information, the field "auth endpoint" should contain "https://chat.mydomain.com/oauth/authorize.php".

If this does not fix your problem, maybe it's a problem with your reverse proxy. Check if you can reach your Oauth server and perform an identification (you can login but you should only see an HTML page).

If you have time, you can set up a proxy to get requests between Mattermost and the Oauth server (MITM proxy, or a browser plugin). You should see precisely what is going on.

I hope this will solve your problem, please let me know,

Good luck

**Comment by Crivaledaz** [comment]
I close this issue since there is no update for one year. Feel free to reopen it if you still have the problem.

Regards
