### ISSUE TITLE
Impossible to get data

### ISSUE THREAD

**Issue by alexmirtoff** [Crivaledaz/Mattermost-LDAP#29]
Hello!

Mattermost 5.10
Have a trouble with auth in AD:

Authentication failed ... Check your username and password.
If error persist contact your administrator.

Click here to come back to login page

{"error":"Impossible to get data","message":"An error has occured during ldap_search execution. Please check parameter of LDAP\/checkLogin."}

How to debug?
Thank you!

**Comment by Crivaledaz** [comment]
Hi,

I never used Mattermost-LDAP with AD, but I have installed Mattermost 5.10 today and Mattermost-LDAP works well with it and LDAP.

Have you tried to use the `ldap.php` file provided at the root of the repository to check AD communication with PHP ?
 If not, you should place this file in your web server directory (`/var/www/html` with Apache). Then, edit it to adapt parameters in head and browse to the file. Error are more explicit.

Otherwise, you can see PHP logs in `/var/log/httpd/error.log` (for CentOS 7), maybe the error is more detailed in this file.

Your error seems due to a permission problem, so verify your account is allowed to perform a search on the AD.

Thanks you for using Mattermost-LDAP, 

Regards

**Comment by chrisjschultz** [comment]
Try the following - this is what I had to do for my AD server.

$ldap_host = "ldap://server:3268/";
$ldap_port = 3268;

**Comment by adocampo** [comment]
I've just found the very same error, and specifying the port also on the URL did the trick! :)
Awesome work folks! :100:

**Comment by alexmirtoff** [comment]
Thank you! I will try it on this week.

**Comment by alexmirtoff** [comment]
It works!

**Comment by jengle02** [comment]
Is anyone using Active Directory to perform these lookups? The syntax of the DN doesn't exactly jive with the format that AD uses e.g. ou=people,dc=domain,dc=com versus ou=people,o=company. The base and bind seem to be my issue at the moment but I'm not sure how to translate AD to LDAP syntax.

**Comment by patrickober** [comment]
This is what i used to test my ldap connection and get things ready to implement in Mattermost-LDAP. 

Though there is a slight modification to the original testldap.php file because i needed to address serveral Base DN's because i was not able to search the entire directory, i don't know if this a specific problem in my setup but it could also be a general Active Directory thing as i encountered the same problem when connecting Nextcloud to AD.

<?php

error_reporting(E_ALL);

###################################---Configuration---################################

//Ldap adress and port
$hostname = "ldaps://domain.local";

//LDAP version
$ldap_version = 3;

//directory name (dn)
$dn = "CN=mattermost,OU=ServiceAccounts,OU=Benutzer,OU=company,DC=domain,DC=local";

//Password (Only for test, we give the password in clear text)
$pass = "ExamplePW";

//ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
$ldapconn = ldap_connect( $hostname )
              or die( "Cannot connect" );
ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);

$base = "OU=Users,DC=company,DC=local";
$bases = ["OU=Verwaltung,DC=company,DC=local","OU=Users,DC=company,DC=local","OU=Admins,DC=company,DC=local"];
######################################################################################
$filter = "(&(objectClass=user)(sAMAccountName=user01)(memberof=CN=Mattermost,OU=Berechtigungsgruppen,OU=Gruppen,OU=Users,DC=company,DC=local))";

echo "<h3>LDAP : Test Center</h3>";
echo "Attempting to connect LDAP server ... <br />";
$ldap=$ldapconn;
ldap_set_option($ldap, LDAP_OPT_PROTOCOL_VERSION, $ldap_version);

if ($ldap) {
    echo "Successful connection ! <br />\r\n";
    echo "Checking LDAP credentials ... <br />\r\n";
    //ldap_start_tls($ldap);
    $is_valid=ldap_bind($ldap,$dn,$pass);

    if ($is_valid) {
        echo "Successful authentication ! <br />\r\n";
        echo "Getting user informations ...<br />\r\n";
        foreach ($bases as $base) {
            try {
                $result = $user_data=ldap_search($ldap, $base, $filter);
            } catch (Exception $result) {
                continue;
            }
            echo "this ->".$result."<-\r\n";
                $info_user = ldap_get_entries($ldap, $user_data);
                        for ($i=0; $i<$info_user["count"]; $i++) {
                echo "XOX.\r\n";
                        echo "dn: " . $info_user[$i]["dn"] . "<br />";
                        echo "cn: " . $info_user[$i]["cn"][0] . "<br />";
                        echo "title: " . $info_user[$i]["title"][0] . "<br />";
                        echo "email: " . $info_user[$i]["mail"][0] . "<br /><hr />";
                        echo "email: " . $info_user[$i]["division"][0] . "<br /><hr />";
                        }
        }
    } else {
                echo "Identification has failed ... Check your credentials<br /><br />";
        }
        echo "Closing LDAP connection.";
    ldap_close($ldap);
} else {
    echo "Impossible to connect to LDAP server !";
}

**Comment by patrickober** [comment]
This is what i used to test my ldap connection and get things ready to implement in Mattermost-LDAP.

Though there is a slight modification to the original testldap.php file because i needed to address serveral Base DN's because i was not able to search the entire directory, i don't know if this a specific problem in my setup but it could also be a general Active Directory thing as i encountered the same problem when connecting Nextcloud to AD.

`
<?php

error_reporting(E_ALL);

###################################---Configuration---################################

//Ldap adress and port
$hostname = "ldaps://domain.local";

//LDAP version
$ldap_version = 3;

//Unique identifier of user on LDAP
$uid = "user01";

//directory name (dn)
$dn = "CN=mattermost,OU=ServiceAccounts,OU=Benutzer,OU=company,DC=domain,DC=local";

//Password (Only for test, we give the password in clear text)
$pass = "ExamplePW";

//ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
$ldapconn = ldap_connect( $hostname )
              or die( "Cannot connect" );
ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);

$base = "OU=Users,DC=company,DC=local";
$bases = ["OU=Verwaltung,DC=company,DC=local","OU=Users,DC=company,DC=local","OU=Admins,DC=company,DC=local"];
######################################################################################
$filter = "(&(objectClass=user)(sAMAccountName=user01)(memberof=CN=Mattermost,OU=Berechtigungsgruppen,OU=Gruppen,OU=Users,DC=company,DC=local))";

echo "<h3>LDAP : Test Center</h3>";
echo "Attempting to connect LDAP server ... <br />";
$ldap=$ldapconn;
ldap_set_option($ldap, LDAP_OPT_PROTOCOL_VERSION, $ldap_version);

if ($ldap) {
    echo "Successful connection ! <br />\r\n";
    echo "Checking LDAP credentials ... <br />\r\n";
    //ldap_start_tls($ldap);
    $is_valid=ldap_bind($ldap,$dn,$pass);

    if ($is_valid) {
        echo "Successful authentication ! <br />\r\n";
        echo "Getting user informations ...<br />\r\n";
        foreach ($bases as $base) {
            try {
                $result = $user_data=ldap_search($ldap, $base, $filter);
            } catch (Exception $result) {
                continue;
            }
            echo "this ->".$result."<-\r\n";
                $info_user = ldap_get_entries($ldap, $user_data);
                        for ($i=0; $i<$info_user["count"]; $i++) {
                echo "XOX.\r\n";
                        echo "dn: " . $info_user[$i]["dn"] . "<br />";
                        echo "cn: " . $info_user[$i]["cn"][0] . "<br />";
                        echo "title: " . $info_user[$i]["title"][0] . "<br />";
                        echo "email: " . $info_user[$i]["mail"][0] . "<br /><hr />";
                        echo "email: " . $info_user[$i]["division"][0] . "<br /><hr />";
                        }
        }
    } else {
                echo "Identification has failed ... Check your credentials<br /><br />";
        }
        echo "Closing LDAP connection.";
    ldap_close($ldap);
} else {
    echo "Impossible to connect to LDAP server !";
}`

**Comment by jengle02** [comment]
Got it working... now to find the solution to this URL /oauth/authorize not found on this server...

**Comment by Catfriend1** [comment]
Our config for MS AD DC with WinServer 2012 R2 is:

```
<?php
// LDAP parameters
$ldap_host = "ldap://company.local:3268/";
$ldap_port = 3268;
$ldap_version = 3;

// Attribute use to identify user on LDAP - ex : uid, mail, sAMAccountName	
$ldap_search_attribute = "sAMAccountName";

// variable use in resource.php 
$ldap_base_dn = "ou=User,ou=COMPANY,dc=company,dc=local";
$ldap_filter = "objectClass=*";

// ldap service user to allow search in ldap
$ldap_bind_dn = "cn=ldap.mattermost,ou=ServiceAccounts,ou=User,ou=COMPANY,dc=company,dc=local";
$ldap_bind_pass = "PASSWORD";
```
