### ISSUE TITLE
Using StartTLS for ldap

### ISSUE THREAD

**Issue by PierreTecher-honhon** [Crivaledaz/Mattermost-LDAP#54]
Hello,

**Is your feature request related to a problem? Please describe.**
I'm trying to use SSL with ldaps as mentionned in the issue https://github.com/Crivaledaz/Mattermost-LDAP/issues/53#issue-645435848 but I face some problems to get through.

**Describe the solution you'd like**
Is it possible to implement a way to use StartTLS for ldap ?

Regards,
Pierre

**Comment by Crivaledaz** [comment]
Hi,

The ldaps and START TLS protocols are not the same. Ldaps is usually exposed on port 636 of the LDAP server and performs a full encrypted communication between the client and the server. While START TLS extend the standard LDAP protocol usually available on port 389 of the LDAP server. It allows the client to ask for an encrypted communication during a clear connection session.

Mattermost-LDAP should support ldaps, even if I have never tested it because I have no LDAP instance with ldaps compatibility. However, if your ldaps certificate is trusted by the oauth client, this should be working. 

Moreover, Mattermost-LDAP doesn't support the START TLS protocol for now, but I just saw a new pull request (#56 ) about your issue have spawned during I was writing this. I just need to perform some tests and I will certainly merge this PR in the next days. It would be nice if you can try the PR and check if it solves your issue.  

Regards,
