### ISSUE TITLE
Deploy using docker 

### ISSUE THREAD

**Issue by zmellal** [Crivaledaz/Mattermost-LDAP#8]

**Comment by Crivaledaz** [comment]
Hi,

I had preferred some more details of your suggest, because it's not easy to know what you really want with a three word title ;)

If I have understood you would like a Docker container with Mattermost and Mattermost-LDAP installed. This will be a good idea, but currently I have no time to create a Docker container. I am sorry :/

Actually, I never used Docker, I only heard about it. Moreover, I never install and configure a LDAP server, because I always use existing LDAP.  So, it could be time consuming for me to discover these two technologies.

Probably, one day I will see about deploy Mattermost-LDAP with docker, in the meantime, I suggest you to use the Puppet module, which provide an easy and efficient way to install Mattermost and Mattermost-LDAP.

Finally, feel free to propose a pull request with the docker container ;)

Regards,

Crivaledaz

**Comment by lnxbil** [comment]
I thought about the same thing ... as far as I understood this oauth-stuff, the php scripts can run wherever you want, as long as they have access to the ldap server, the postgresql database and mattermost (and vice versa), so you only "need" a webserver (preferably with SSL) and a database. This can be done with Docker with ease. The good thing about docker is that it normally has all the necessary commands to setup everything, so Docker could be a second "how to do it" instruction manual.

Best would be if @zmellal could provide the necessary `Dockerfile` for that.

**Comment by DavidAntliff** [comment]
Would this help?

https://github.com/emudome/mattermost-ldap-docker

**Comment by colinleroy** [comment]
BTW, I've made a pull request for that :)

**Comment by Crivaledaz** [comment]
Hi,

Thank you very much for your work and your effort to dockerize Mattermost-LDAP. 

However, I have already dockerized Mattemost-LDAP, three months ago, and I am using it in a Kubernetes cluster. I am also working on a Helm module to deploy easily Mattermost-LDAP in a Kubernetes cluster.

I have not pushed the Dockerfiles because I want to write a clear Readme to explain how to use these Docker images. I took a quick look on your work, and there are some interesting things, especially on Docker compose.

I wish I could finish the Readme this week, and push it as soon as possible. I will be happy if you can complete my work with your work  and make it consistent with Docker compose.

Thank you again for your work, I will get back to you when I push my work.

Regards,

**Comment by colinleroy** [comment]
Hi,
Thanks for the update !

**Comment by Crivaledaz** [comment]
Hi,

I finally find some time (and motivation, thanks to you ;) ) to finish my Docker module. I have pushed it on the [Docker folder](https://github.com/Crivaledaz/Mattermost-LDAP/tree/master/Docker).

The main difference with your Dockerfile is that I use a separate container for the database, like Mattermost do. This allows to update/change Oauth server with minimal impact on the data.

Moreover, I choose to configure LDAP and the Database via environment parameters to avoid building image each time. This is easier also for Kubernetes and Helm use.  

I would appreciate every feedback and suggestion to improve it. Feel free to comment here or to make a new pull request.

**Comment by C-Duv** [comment]
Thanks for the Docker module.
A `docker-compose.yml` could be useful: I'll try to create one.

**Comment by Crivaledaz** [comment]
Hi,

Mattermost-LDAP containers have been updated and simplified in V2. Moreover, a `docker-compose` is also available in the V2. 

I close this issue since Docker and Docker-Compose have been integrated in Mattermost-LDAP V2.

Thank you for your suggestions and help,

Regards
